version: "3"

services:
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: eniqilodb
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5430:5432"
  api:
    container_name: api_dockerizing
    build: .
    ports:
      - 8080:8080
    image: dionfananie/eniqilo-store:1.0
    env_file: .env.docker
    restart: always
    volumes:
      - api_volume:/usr/src/app/
    # depends_on:
    #   - postgres

volumes:
  # database_dockerizing:
  api_volume:
# networks:
#   fullstack:
#     driver: bridge
