version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: eniqilodb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5430:5432"
  api:
    container_name: api_dockerizing
    build: .
    ports:
      - 8080:8080
    environment:
      DB_NAME: eniqilodb
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
      JWT_SECRET: zay1kkxK6l7Z/4ldpltMawLBmIYyyio+CRrhRLzk8HijZS114h8gw6MX5Udi2X3ZP+B9B9aFWdTdGl83DbC6tqflT+bR+laM5X9QNacTXzNlmZZtbxGM3PKkdOe7KSuR4BgdNiGig5aLFQykZfZLpWuoGXTfhwmIIgNeR5fVN6MGkz9Zr5GAdVRv5kIzgoY875ZYsyR85EEMyABwAfpc69K4dGTg==
      JWT_EXP: 8h
      BCRYPT_SALT: 8
    restart: always
    volumes:
      - api_volume:/usr/src/app/
    depends_on:
      - postgres

volumes:
  # database_dockerizing:
  api_volume:
# networks:
#   fullstack:
#     driver: bridge
